version: 2.0
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update -q
            apt install -y sudo rsync gawk unzip libncurses-dev libz-dev libssl-dev wget time
      - checkout:
          name: Checkout
      - run:
          name: Compile
          environment:
            GLUON_SITEDIR: "docs/site-example"
            GLUON_TARGET: "x86-generic"
            BUILD_LOG: "1"
          command: |
            useradd build
            rsync -a $HOME/.ssh /home/build/
            chmod 755 /root
            chown -R build: . /home/build/
            ls -la /home/build/
            ls -la /home/build/.ssh/
            sudo -u build -E make update
            sudo -u build -E make download -j4
            sudo -u build -E make -j4 || sudo -u build -E make -j1 V=s
